LILYPOND-BOOK=lilypond-book -o out --pdf
LATEX=xelatex

all: 2Sun 3Sun 4Sun 5Sun 6Sun 7Sun 8Sun 9Sun 10Sun 11Sun 12Sun 13Sun 14Sun 15Sun 16Sun 17Sun 18Sun 19Sun 20Sun 21Sun 22Sun 23Sun 24Sun 25Sun 26Sun 27Sun 28Sun 29Sun 30Sun 31Sun 32Sun 33Sun

33Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 33Sun-Organ.lytex
	cd out && $(LATEX) 33Sun-Organ.tex
	cd out && xdg-open 33Sun-Organ.pdf
	$(LILYPOND-BOOK) 33Sun-Cantor.lytex
	cd out && $(LATEX) 33Sun-Cantor.tex
	cd out && xdg-open 33Sun-Cantor.pdf

32Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 32Sun-Organ.lytex
	cd out && $(LATEX) 32Sun-Organ.tex
	cd out && xdg-open 32Sun-Organ.pdf
	$(LILYPOND-BOOK) 32Sun-Cantor.lytex
	cd out && $(LATEX) 32Sun-Cantor.tex
	cd out && xdg-open 32Sun-Cantor.pdf

31Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 31Sun-Organ.lytex
	cd out && $(LATEX) 31Sun-Organ.tex
	cd out && xdg-open 31Sun-Organ.pdf
	$(LILYPOND-BOOK) 31Sun-Cantor.lytex
	cd out && $(LATEX) 31Sun-Cantor.tex
	cd out && xdg-open 31Sun-Cantor.pdf

30Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 30Sun-Organ.lytex
	cd out && $(LATEX) 30Sun-Organ.tex
	cd out && xdg-open 30Sun-Organ.pdf
	$(LILYPOND-BOOK) 30Sun-Cantor.lytex
	cd out && $(LATEX) 30Sun-Cantor.tex
	cd out && xdg-open 30Sun-Cantor.pdf

29Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 29Sun-Organ.lytex
	cd out && $(LATEX) 29Sun-Organ.tex
	cd out && xdg-open 29Sun-Organ.pdf
	$(LILYPOND-BOOK) 29Sun-Cantor.lytex
	cd out && $(LATEX) 29Sun-Cantor.tex
	cd out && xdg-open 29Sun-Cantor.pdf

28Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 28Sun-Organ.lytex
	cd out && $(LATEX) 28Sun-Organ.tex
	cd out && xdg-open 28Sun-Organ.pdf
	$(LILYPOND-BOOK) 28Sun-Cantor.lytex
	cd out && $(LATEX) 28Sun-Cantor.tex
	cd out && xdg-open 28Sun-Cantor.pdf

27Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 27Sun-Organ.lytex
	cd out && $(LATEX) 27Sun-Organ.tex
	cd out && xdg-open 27Sun-Organ.pdf
	$(LILYPOND-BOOK) 27Sun-Cantor.lytex
	cd out && $(LATEX) 27Sun-Cantor.tex
	cd out && xdg-open 27Sun-Cantor.pdf

26Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 26Sun-Organ.lytex
	cd out && $(LATEX) 26Sun-Organ.tex
	cd out && xdg-open 26Sun-Organ.pdf
	$(LILYPOND-BOOK) 26Sun-Cantor.lytex
	cd out && $(LATEX) 26Sun-Cantor.tex
	cd out && xdg-open 26Sun-Cantor.pdf

25Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 25Sun-Organ.lytex
	cd out && $(LATEX) 25Sun-Organ.tex
	cd out && xdg-open 25Sun-Organ.pdf
	$(LILYPOND-BOOK) 25Sun-Cantor.lytex
	cd out && $(LATEX) 25Sun-Cantor.tex
	cd out && xdg-open 25Sun-Cantor.pdf

24Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 24Sun-Organ.lytex
	cd out && $(LATEX) 24Sun-Organ.tex
	cd out && xdg-open 24Sun-Organ.pdf
	$(LILYPOND-BOOK) 24Sun-Cantor.lytex
	cd out && $(LATEX) 24Sun-Cantor.tex
	cd out && xdg-open 24Sun-Cantor.pdf

23Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 23Sun-Organ.lytex
	cd out && $(LATEX) 23Sun-Organ.tex
	cd out && xdg-open 23Sun-Organ.pdf
	$(LILYPOND-BOOK) 23Sun-Cantor.lytex
	cd out && $(LATEX) 23Sun-Cantor.tex
	cd out && xdg-open 23Sun-Cantor.pdf

22Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 22Sun-Organ.lytex
	cd out && $(LATEX) 22Sun-Organ.tex
	cd out && xdg-open 22Sun-Organ.pdf
	$(LILYPOND-BOOK) 22Sun-Cantor.lytex
	cd out && $(LATEX) 22Sun-Cantor.tex
	cd out && xdg-open 22Sun-Cantor.pdf

21Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 21Sun-Organ.lytex
	cd out && $(LATEX) 21Sun-Organ.tex
	cd out && xdg-open 21Sun-Organ.pdf
	$(LILYPOND-BOOK) 21Sun-Cantor.lytex
	cd out && $(LATEX) 21Sun-Cantor.tex
	cd out && xdg-open 21Sun-Cantor.pdf

20Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 20Sun-Organ.lytex
	cd out && $(LATEX) 20Sun-Organ.tex
	cd out && xdg-open 20Sun-Organ.pdf
	$(LILYPOND-BOOK) 20Sun-Cantor.lytex
	cd out && $(LATEX) 20Sun-Cantor.tex
	cd out && xdg-open 20Sun-Cantor.pdf

19Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 19Sun-Organ.lytex
	cd out && $(LATEX) 19Sun-Organ.tex
	cd out && xdg-open 19Sun-Organ.pdf
	$(LILYPOND-BOOK) 19Sun-Cantor.lytex
	cd out && $(LATEX) 19Sun-Cantor.tex
	cd out && xdg-open 19Sun-Cantor.pdf

18Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 18Sun-Organ.lytex
	cd out && $(LATEX) 18Sun-Organ.tex
	cd out && xdg-open 18Sun-Organ.pdf
	$(LILYPOND-BOOK) 18Sun-Cantor.lytex
	cd out && $(LATEX) 18Sun-Cantor.tex
	cd out && xdg-open 18Sun-Cantor.pdf

17Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 17Sun-Organ.lytex
	cd out && $(LATEX) 17Sun-Organ.tex
	cd out && xdg-open 17Sun-Organ.pdf
	$(LILYPOND-BOOK) 17Sun-Cantor.lytex
	cd out && $(LATEX) 17Sun-Cantor.tex
	cd out && xdg-open 17Sun-Cantor.pdf

16Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 16Sun-Organ.lytex
	cd out && $(LATEX) 16Sun-Organ.tex
	cd out && xdg-open 16Sun-Organ.pdf
	$(LILYPOND-BOOK) 16Sun-Cantor.lytex
	cd out && $(LATEX) 16Sun-Cantor.tex
	cd out && xdg-open 16Sun-Cantor.pdf

15Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 15Sun-Organ.lytex
	cd out && $(LATEX) 15Sun-Organ.tex
	cd out && xdg-open 15Sun-Organ.pdf
	$(LILYPOND-BOOK) 15Sun-Cantor.lytex
	cd out && $(LATEX) 15Sun-Cantor.tex
	cd out && xdg-open 15Sun-Cantor.pdf

14Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 14Sun-Organ.lytex
	cd out && $(LATEX) 14Sun-Organ.tex
	cd out && xdg-open 14Sun-Organ.pdf
	$(LILYPOND-BOOK) 14Sun-Cantor.lytex
	cd out && $(LATEX) 14Sun-Cantor.tex
	cd out && xdg-open 14Sun-Cantor.pdf

13Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 13Sun-Organ.lytex
	cd out && $(LATEX) 13Sun-Organ.tex
	cd out && xdg-open 13Sun-Organ.pdf
	$(LILYPOND-BOOK) 13Sun-Cantor.lytex
	cd out && $(LATEX) 13Sun-Cantor.tex
	cd out && xdg-open 13Sun-Cantor.pdf

12Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 12Sun-Organ.lytex
	cd out && $(LATEX) 12Sun-Organ.tex
	cd out && xdg-open 12Sun-Organ.pdf
	$(LILYPOND-BOOK) 12Sun-Cantor.lytex
	cd out && $(LATEX) 12Sun-Cantor.tex
	cd out && xdg-open 12Sun-Cantor.pdf

11Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 11Sun-Organ.lytex
	cd out && $(LATEX) 11Sun-Organ.tex
	cd out && xdg-open 11Sun-Organ.pdf
	$(LILYPOND-BOOK) 11Sun-Cantor.lytex
	cd out && $(LATEX) 11Sun-Cantor.tex
	cd out && xdg-open 11Sun-Cantor.pdf

10Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 10Sun-Organ.lytex
	cd out && $(LATEX) 10Sun-Organ.tex
	cd out && xdg-open 10Sun-Organ.pdf
	$(LILYPOND-BOOK) 10Sun-Cantor.lytex
	cd out && $(LATEX) 10Sun-Cantor.tex
	cd out && xdg-open 10Sun-Cantor.pdf

9Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 9Sun-Organ.lytex
	cd out && $(LATEX) 9Sun-Organ.tex
	cd out && xdg-open 9Sun-Organ.pdf
	$(LILYPOND-BOOK) 9Sun-Cantor.lytex
	cd out && $(LATEX) 9Sun-Cantor.tex
	cd out && xdg-open 9Sun-Cantor.pdf

8Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 8Sun-Organ.lytex
	cd out && $(LATEX) 8Sun-Organ.tex
	cd out && xdg-open 8Sun-Organ.pdf
	$(LILYPOND-BOOK) 8Sun-Cantor.lytex
	cd out && $(LATEX) 8Sun-Cantor.tex
	cd out && xdg-open 8Sun-Cantor.pdf

7Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 7Sun-Organ.lytex
	cd out && $(LATEX) 7Sun-Organ.tex
	cd out && xdg-open 7Sun-Organ.pdf
	$(LILYPOND-BOOK) 7Sun-Cantor.lytex
	cd out && $(LATEX) 7Sun-Cantor.tex
	cd out && xdg-open 7Sun-Cantor.pdf

6Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 6Sun-Organ.lytex
	cd out && $(LATEX) 6Sun-Organ.tex
	cd out && xdg-open 6Sun-Organ.pdf
	$(LILYPOND-BOOK) 6Sun-Cantor.lytex
	cd out && $(LATEX) 6Sun-Cantor.tex
	cd out && xdg-open 6Sun-Cantor.pdf

5Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 5Sun-Organ.lytex
	cd out && $(LATEX) 5Sun-Organ.tex
	cd out && xdg-open 5Sun-Organ.pdf
	$(LILYPOND-BOOK) 5Sun-Cantor.lytex
	cd out && $(LATEX) 5Sun-Cantor.tex
	cd out && xdg-open 5Sun-Cantor.pdf

4Sun:
	rm -rf out/*/
	$(LILYPOND-BOOK) 4Sun-Organ.lytex
	cd out && $(LATEX) 4Sun-Organ.tex
	cd out && xdg-open 4Sun-Organ.pdf
	$(LILYPOND-BOOK) 4Sun-Cantor.lytex
	cd out && $(LATEX) 4Sun-Cantor.tex
	cd out && xdg-open 4Sun-Cantor.pdf

3Sun:
	$(LILYPOND-BOOK) 3Sun-Organ.lytex
	cd out && $(LATEX) 3Sun-Organ.tex
	cd out && xdg-open 3Sun-Organ.pdf
	$(LILYPOND-BOOK) 3Sun-Cantor.lytex
	cd out && $(LATEX) 3Sun-Cantor.tex
	cd out && xdg-open 3Sun-Cantor.pdf

2Sun:
	$(LILYPOND-BOOK) 2Sun-Organ.lytex
	cd out && $(LATEX) 2Sun-Organ.tex
	cd out && xdg-open 2Sun-Organ.pdf
	$(LILYPOND-BOOK) 2Sun-Cantor.lytex
	cd out && $(LATEX) 2Sun-Cantor.tex
	cd out && xdg-open 2Sun-Cantor.pdf
