LILYPOND-BOOK=lilypond-book -o out --pdf
LATEX=xelatex
LUATEX=lualatex -shell-escape

temp:
	# rm -rf tmp-ly/*.*
	$(LUATEX) ScoreCantor.tex
	evince ScoreCantor.pdf
	# $(LUATEX) ScoreOrgan.tex
	# evince ScoreOrgan.pdf


# all: 2Sun 3Sun 4Sun 5Sun 6Sun 7Sun 8Sun 9Sun 10Sun 11Sun 12Sun 13Sun 14Sun 15Sun 16Sun 17Sun 18Sun 19Sun 20Sun 21Sun 22Sun 23Sun 24Sun 25Sun 26Sun 27Sun 28Sun 29Sun 30Sun 31Sun 32Sun 33Sun

# 33Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 33Sun-Organ.lytex
# 	cd out && $(LATEX) 33Sun-Organ.tex
# 	$(LILYPOND-BOOK) 33Sun-Cantor.lytex
# 	cd out && $(LATEX) 33Sun-Cantor.tex

# 32Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 32Sun-Organ.lytex
# 	cd out && $(LATEX) 32Sun-Organ.tex
# 	$(LILYPOND-BOOK) 32Sun-Cantor.lytex
# 	cd out && $(LATEX) 32Sun-Cantor.tex

# 31Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 31Sun-Organ.lytex
# 	cd out && $(LATEX) 31Sun-Organ.tex
# 	$(LILYPOND-BOOK) 31Sun-Cantor.lytex
# 	cd out && $(LATEX) 31Sun-Cantor.tex

# 30Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 30Sun-Organ.lytex
# 	cd out && $(LATEX) 30Sun-Organ.tex
# 	$(LILYPOND-BOOK) 30Sun-Cantor.lytex
# 	cd out && $(LATEX) 30Sun-Cantor.tex

# 29Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 29Sun-Organ.lytex
# 	cd out && $(LATEX) 29Sun-Organ.tex
# 	$(LILYPOND-BOOK) 29Sun-Cantor.lytex
# 	cd out && $(LATEX) 29Sun-Cantor.tex

# 28Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 28Sun-Organ.lytex
# 	cd out && $(LATEX) 28Sun-Organ.tex
# 	$(LILYPOND-BOOK) 28Sun-Cantor.lytex
# 	cd out && $(LATEX) 28Sun-Cantor.tex

# 27Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 27Sun-Organ.lytex
# 	cd out && $(LATEX) 27Sun-Organ.tex
# 	$(LILYPOND-BOOK) 27Sun-Cantor.lytex
# 	cd out && $(LATEX) 27Sun-Cantor.tex

# 26Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 26Sun-Organ.lytex
# 	cd out && $(LATEX) 26Sun-Organ.tex
# 	$(LILYPOND-BOOK) 26Sun-Cantor.lytex
# 	cd out && $(LATEX) 26Sun-Cantor.tex

# 25Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 25Sun-Organ.lytex
# 	cd out && $(LATEX) 25Sun-Organ.tex
# 	$(LILYPOND-BOOK) 25Sun-Cantor.lytex
# 	cd out && $(LATEX) 25Sun-Cantor.tex

# 24Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 24Sun-Organ.lytex
# 	cd out && $(LATEX) 24Sun-Organ.tex
# 	$(LILYPOND-BOOK) 24Sun-Cantor.lytex
# 	cd out && $(LATEX) 24Sun-Cantor.tex

# 23Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 23Sun-Organ.lytex
# 	cd out && $(LATEX) 23Sun-Organ.tex
# 	$(LILYPOND-BOOK) 23Sun-Cantor.lytex
# 	cd out && $(LATEX) 23Sun-Cantor.tex

# 22Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 22Sun-Organ.lytex
# 	cd out && $(LATEX) 22Sun-Organ.tex
# 	$(LILYPOND-BOOK) 22Sun-Cantor.lytex
# 	cd out && $(LATEX) 22Sun-Cantor.tex

# 21Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 21Sun-Organ.lytex
# 	cd out && $(LATEX) 21Sun-Organ.tex
# 	$(LILYPOND-BOOK) 21Sun-Cantor.lytex
# 	cd out && $(LATEX) 21Sun-Cantor.tex

# 20Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 20Sun-Organ.lytex
# 	cd out && $(LATEX) 20Sun-Organ.tex
# 	$(LILYPOND-BOOK) 20Sun-Cantor.lytex
# 	cd out && $(LATEX) 20Sun-Cantor.tex

# 19Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 19Sun-Organ.lytex
# 	cd out && $(LATEX) 19Sun-Organ.tex
# 	$(LILYPOND-BOOK) 19Sun-Cantor.lytex
# 	cd out && $(LATEX) 19Sun-Cantor.tex

# 18Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 18Sun-Organ.lytex
# 	cd out && $(LATEX) 18Sun-Organ.tex
# 	$(LILYPOND-BOOK) 18Sun-Cantor.lytex
# 	cd out && $(LATEX) 18Sun-Cantor.tex

# 17Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 17Sun-Organ.lytex
# 	cd out && $(LATEX) 17Sun-Organ.tex
# 	$(LILYPOND-BOOK) 17Sun-Cantor.lytex
# 	cd out && $(LATEX) 17Sun-Cantor.tex

# 16Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 16Sun-Organ.lytex
# 	cd out && $(LATEX) 16Sun-Organ.tex
# 	$(LILYPOND-BOOK) 16Sun-Cantor.lytex
# 	cd out && $(LATEX) 16Sun-Cantor.tex

# 15Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 15Sun-Organ.lytex
# 	cd out && $(LATEX) 15Sun-Organ.tex
# 	$(LILYPOND-BOOK) 15Sun-Cantor.lytex
# 	cd out && $(LATEX) 15Sun-Cantor.tex

# 14Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 14Sun-Organ.lytex
# 	cd out && $(LATEX) 14Sun-Organ.tex
# 	$(LILYPOND-BOOK) 14Sun-Cantor.lytex
# 	cd out && $(LATEX) 14Sun-Cantor.tex

# 13Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 13Sun-Organ.lytex
# 	cd out && $(LATEX) 13Sun-Organ.tex
# 	$(LILYPOND-BOOK) 13Sun-Cantor.lytex
# 	cd out && $(LATEX) 13Sun-Cantor.tex

# 12Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 12Sun-Organ.lytex
# 	cd out && $(LATEX) 12Sun-Organ.tex
# 	$(LILYPOND-BOOK) 12Sun-Cantor.lytex
# 	cd out && $(LATEX) 12Sun-Cantor.tex

# 11Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 11Sun-Organ.lytex
# 	cd out && $(LATEX) 11Sun-Organ.tex
# 	$(LILYPOND-BOOK) 11Sun-Cantor.lytex
# 	cd out && $(LATEX) 11Sun-Cantor.tex

# 10Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 10Sun-Organ.lytex
# 	cd out && $(LATEX) 10Sun-Organ.tex
# 	$(LILYPOND-BOOK) 10Sun-Cantor.lytex
# 	cd out && $(LATEX) 10Sun-Cantor.tex

# 9Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 9Sun-Organ.lytex
# 	cd out && $(LATEX) 9Sun-Organ.tex
# 	$(LILYPOND-BOOK) 9Sun-Cantor.lytex
# 	cd out && $(LATEX) 9Sun-Cantor.tex

# 8Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 8Sun-Organ.lytex
# 	cd out && $(LATEX) 8Sun-Organ.tex
# 	$(LILYPOND-BOOK) 8Sun-Cantor.lytex
# 	cd out && $(LATEX) 8Sun-Cantor.tex

# 7Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 7Sun-Organ.lytex
# 	cd out && $(LATEX) 7Sun-Organ.tex
# 	$(LILYPOND-BOOK) 7Sun-Cantor.lytex
# 	cd out && $(LATEX) 7Sun-Cantor.tex

# 6Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 6Sun-Organ.lytex
# 	cd out && $(LATEX) 6Sun-Organ.tex
# 	$(LILYPOND-BOOK) 6Sun-Cantor.lytex
# 	cd out && $(LATEX) 6Sun-Cantor.tex

# 5Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 5Sun-Organ.lytex
# 	cd out && $(LATEX) 5Sun-Organ.tex
# 	$(LILYPOND-BOOK) 5Sun-Cantor.lytex
# 	cd out && $(LATEX) 5Sun-Cantor.tex

# 4Sun:
# 	rm -rf out/*/
# 	$(LILYPOND-BOOK) 4Sun-Organ.lytex
# 	cd out && $(LATEX) 4Sun-Organ.tex
# 	$(LILYPOND-BOOK) 4Sun-Cantor.lytex
# 	cd out && $(LATEX) 4Sun-Cantor.tex

# 3Sun:
# 	$(LILYPOND-BOOK) 3Sun-Organ.lytex
# 	cd out && $(LATEX) 3Sun-Organ.tex
# 	$(LILYPOND-BOOK) 3Sun-Cantor.lytex
# 	cd out && $(LATEX) 3Sun-Cantor.tex

# 2Sun:
# 	$(LILYPOND-BOOK) 2Sun-Organ.lytex
# 	cd out && $(LATEX) 2Sun-Organ.tex
# 	$(LILYPOND-BOOK) 2Sun-Cantor.lytex
# 	cd out && $(LATEX) 2Sun-Cantor.tex
